### ISSUE TITLE
Compile error for stream_decode.cc

### ISSUE THREAD

**Issue by jamesbiv** [pure-css/pure#749]
Hi Guys

I have encountered the following compile error when attempting a build

```
../src/dec/stream_decode.cc: In constructor 'StreamDecode::StreamDecode(v8::Local<v8::Object>)':
../src/dec/stream_decode.cc:14:81: error: no matching function for call to 'v8::Value::ToObject()'
     Local<Object> dictionary = Nan::Get(params, key).ToLocalChecked()->ToObject();
```

OS version
```
~/pure$ uname -a
Linux devuan-server01 5.0.5 #1 SMP Fri Mar 29 19:58:38 -03 2019 x86_64 GNU/Linux
```
Full output as below

```
~$ git clone https://github.com/pure-css/pure.git
Cloning into 'pure'...
remote: Enumerating objects: 2723, done.
remote: Total 2723 (delta 0), reused 0 (delta 0), pack-reused 2723
Receiving objects: 100% (2723/2723), 455.35 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1350/1350), done.
Checking connectivity... done.
~$ cd pure
~/pure$ npm install
npm WARN deprecated bower@1.8.8: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated coffee-script@1.3.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> iltorb@1.3.10 install /home/james/pure/node_modules/iltorb
> detect-libc prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=12.4.0 runtime=node arch=x64 platform=linux)
make: Entering directory '/home/james/pure/node_modules/iltorb/build'
  CC(target) Release/obj.target/iltorb/brotli/common/dictionary.o
  CC(target) Release/obj.target/iltorb/brotli/dec/bit_reader.o
  CC(target) Release/obj.target/iltorb/brotli/dec/decode.o
  CC(target) Release/obj.target/iltorb/brotli/dec/huffman.o
  CC(target) Release/obj.target/iltorb/brotli/dec/state.o
  CC(target) Release/obj.target/iltorb/brotli/enc/backward_references.o
  CC(target) Release/obj.target/iltorb/brotli/enc/backward_references_hq.o
  CC(target) Release/obj.target/iltorb/brotli/enc/bit_cost.o
  CC(target) Release/obj.target/iltorb/brotli/enc/block_splitter.o
  CC(target) Release/obj.target/iltorb/brotli/enc/brotli_bit_stream.o
  CC(target) Release/obj.target/iltorb/brotli/enc/cluster.o
  CC(target) Release/obj.target/iltorb/brotli/enc/compress_fragment.o
  CC(target) Release/obj.target/iltorb/brotli/enc/compress_fragment_two_pass.o
  CC(target) Release/obj.target/iltorb/brotli/enc/dictionary_hash.o
  CC(target) Release/obj.target/iltorb/brotli/enc/encode.o
  CC(target) Release/obj.target/iltorb/brotli/enc/entropy_encode.o
  CC(target) Release/obj.target/iltorb/brotli/enc/histogram.o
  CC(target) Release/obj.target/iltorb/brotli/enc/literal_cost.o
  CC(target) Release/obj.target/iltorb/brotli/enc/memory.o
  CC(target) Release/obj.target/iltorb/brotli/enc/metablock.o
  CC(target) Release/obj.target/iltorb/brotli/enc/static_dict.o
  CC(target) Release/obj.target/iltorb/brotli/enc/utf8_util.o
  CXX(target) Release/obj.target/iltorb/src/common/allocator.o
  CXX(target) Release/obj.target/iltorb/src/common/stream_coder.o
  CXX(target) Release/obj.target/iltorb/src/dec/stream_decode.o
../src/dec/stream_decode.cc: In constructor 'StreamDecode::StreamDecode(v8::Local<v8::Object>)':
../src/dec/stream_decode.cc:14:81: error: no matching function for call to 'v8::Value::ToObject()'
     Local<Object> dictionary = Nan::Get(params, key).ToLocalChecked()->ToObject();
                                                                                 ^
../src/dec/stream_decode.cc:14:81: note: candidates are:
In file included from /home/james/.node-gyp/12.4.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/dec/stream_decode.h:4,
                 from ../src/dec/stream_decode.cc:1:
/home/james/.node-gyp/12.4.0/include/node/v8.h:2532:44: note: v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^
/home/james/.node-gyp/12.4.0/include/node/v8.h:2532:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/james/.node-gyp/12.4.0/include/node/v8-internal.h:14:0,
                 from /home/james/.node-gyp/12.4.0/include/node/v8.h:25,
                 from /home/james/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/dec/stream_decode.h:4,
                 from ../src/dec/stream_decode.cc:1:
/home/james/.node-gyp/12.4.0/include/node/v8.h:2546:35: note: v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^
/home/james/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^
/home/james/.node-gyp/12.4.0/include/node/v8.h:2546:35: note:   candidate expects 1 argument, 0 provided
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^
/home/james/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^
../src/dec/stream_decode.cc: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE StreamDecode::New(Nan::NAN_METHOD_ARGS_TYPE)':
../src/dec/stream_decode.cc:40:58: error: no matching function for call to 'v8::Value::ToObject()'
   StreamDecode* obj = new StreamDecode(info[0]->ToObject());
                                                          ^
../src/dec/stream_decode.cc:40:58: note: candidates are:
In file included from /home/james/.node-gyp/12.4.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/dec/stream_decode.h:4,
                 from ../src/dec/stream_decode.cc:1:
/home/james/.node-gyp/12.4.0/include/node/v8.h:2532:44: note: v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^
/home/james/.node-gyp/12.4.0/include/node/v8.h:2532:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/james/.node-gyp/12.4.0/include/node/v8-internal.h:14:0,
                 from /home/james/.node-gyp/12.4.0/include/node/v8.h:25,
                 from /home/james/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/dec/stream_decode.h:4,
                 from ../src/dec/stream_decode.cc:1:
/home/james/.node-gyp/12.4.0/include/node/v8.h:2546:35: note: v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^
/home/james/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^
/home/james/.node-gyp/12.4.0/include/node/v8.h:2546:35: note:   candidate expects 1 argument, 0 provided
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^
/home/james/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^
../src/dec/stream_decode.cc: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE StreamDecode::Transform(Nan::NAN_METHOD_ARGS_TYPE)':
../src/dec/stream_decode.cc:48:44: error: no matching function for call to 'v8::Value::ToObject()'
   Local<Object> buffer = info[0]->ToObject();
                                            ^
../src/dec/stream_decode.cc:48:44: note: candidates are:
In file included from /home/james/.node-gyp/12.4.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/dec/stream_decode.h:4,
                 from ../src/dec/stream_decode.cc:1:
/home/james/.node-gyp/12.4.0/include/node/v8.h:2532:44: note: v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^
/home/james/.node-gyp/12.4.0/include/node/v8.h:2532:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/james/.node-gyp/12.4.0/include/node/v8-internal.h:14:0,
                 from /home/james/.node-gyp/12.4.0/include/node/v8.h:25,
                 from /home/james/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/dec/stream_decode.h:4,
                 from ../src/dec/stream_decode.cc:1:
/home/james/.node-gyp/12.4.0/include/node/v8.h:2546:35: note: v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^
/home/james/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^
/home/james/.node-gyp/12.4.0/include/node/v8.h:2546:35: note:   candidate expects 1 argument, 0 provided
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^
/home/james/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^
../src/dec/stream_decode.cc:54:29: error: no matching function for call to 'v8::Value::BooleanValue()'
   if (info[2]->BooleanValue()) {
                             ^
../src/dec/stream_decode.cc:54:29: note: candidates are:
In file included from /home/james/.node-gyp/12.4.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/dec/stream_decode.h:4,
                 from ../src/dec/stream_decode.cc:1:
/home/james/.node-gyp/12.4.0/include/node/v8.h:2559:8: note: bool v8::Value::BooleanValue(v8::Isolate*) const
   bool BooleanValue(Isolate* isolate) const;
        ^
/home/james/.node-gyp/12.4.0/include/node/v8.h:2559:8: note:   candidate expects 1 argument, 0 provided
In file included from /home/james/.node-gyp/12.4.0/include/node/v8-internal.h:14:0,
                 from /home/james/.node-gyp/12.4.0/include/node/v8.h:25,
                 from /home/james/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/dec/stream_decode.h:4,
                 from ../src/dec/stream_decode.cc:1:
/home/james/.node-gyp/12.4.0/include/node/v8.h:2562:51: note: v8::Maybe<bool> v8::Value::BooleanValue(v8::Local<v8::Context>) const
                 V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                   ^
/home/james/.node-gyp/12.4.0/include/node/v8config.h:307:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
/home/james/.node-gyp/12.4.0/include/node/v8.h:2562:51: note:   candidate expects 1 argument, 0 provided
                 V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                   ^
/home/james/.node-gyp/12.4.0/include/node/v8config.h:307:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
../src/dec/stream_decode.cc: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE StreamDecode::Flush(Nan::NAN_METHOD_ARGS_TYPE)':
../src/dec/stream_decode.cc:70:29: error: no matching function for call to 'v8::Value::BooleanValue()'
   if (info[1]->BooleanValue()) {
                             ^
../src/dec/stream_decode.cc:70:29: note: candidates are:
In file included from /home/james/.node-gyp/12.4.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/dec/stream_decode.h:4,
                 from ../src/dec/stream_decode.cc:1:
/home/james/.node-gyp/12.4.0/include/node/v8.h:2559:8: note: bool v8::Value::BooleanValue(v8::Isolate*) const
   bool BooleanValue(Isolate* isolate) const;
        ^
/home/james/.node-gyp/12.4.0/include/node/v8.h:2559:8: note:   candidate expects 1 argument, 0 provided
In file included from /home/james/.node-gyp/12.4.0/include/node/v8-internal.h:14:0,
                 from /home/james/.node-gyp/12.4.0/include/node/v8.h:25,
                 from /home/james/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/dec/stream_decode.h:4,
                 from ../src/dec/stream_decode.cc:1:
/home/james/.node-gyp/12.4.0/include/node/v8.h:2562:51: note: v8::Maybe<bool> v8::Value::BooleanValue(v8::Local<v8::Context>) const
                 V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                   ^
/home/james/.node-gyp/12.4.0/include/node/v8config.h:307:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
/home/james/.node-gyp/12.4.0/include/node/v8.h:2562:51: note:   candidate expects 1 argument, 0 provided
                 V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                   ^
/home/james/.node-gyp/12.4.0/include/node/v8config.h:307:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
iltorb.target.mk:141: recipe for target 'Release/obj.target/iltorb/src/dec/stream_decode.o' failed
make: *** [Release/obj.target/iltorb/src/dec/stream_decode.o] Error 1
make: Leaving directory '/home/james/pure/node_modules/iltorb/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.0.5
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/james/pure/node_modules/iltorb
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> purecss@1.0.1 prepublish /home/james/pure
> grunt release


  Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option cause some error. Browserslist config 
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist


Running "bower_install" task
bower install normalize-css#3.0.3

Running "csslint:base" (csslint) task
>> 1 file lint free.

Running "csslint:buttons" (csslint) task
>> 2 files lint free.

Running "csslint:forms" (csslint) task
>> 2 files lint free.

Running "csslint:grids" (csslint) task
>> 1 file lint free.

Running "csslint:menus" (csslint) task
>> 5 files lint free.

Running "csslint:tables" (csslint) task
>> 1 file lint free.

Running "clean:build" (clean) task
>> 0 paths cleaned.

Running "copy:build" (copy) task
Copied 12 files

Running "pure_grids:default_units" (pure_grids) task
File "build/grids-units.css" created.

Running "pure_grids:responsive" (pure_grids) task
File "build/grids-responsive.css" created.

Running "stripmq:all" (stripmq) task
File "build/grids-responsive-old-ie.css" created.

Running "concat:build" (concat) task

Running "clean:build_res" (clean) task
>> 1 path cleaned.

Running "css_selectors:base" (css_selectors) task
File "build/base-context.css" created.

Running "postcss:dist" (postcss) task
>> 20 processed stylesheets created.

Running "cssmin:files" (cssmin) task
>> 20 files created. 142.04 kB → 76.96 kB

Running "license:normalize" (license) task
Stamped license on 8 files.

Running "license:yahoo" (license) task
Stamped license on 40 files.

Running "clean:release" (clean) task
>> 0 paths cleaned.

Running "copy:release" (copy) task
Copied 2 files

Running "bower_json:release" (bower_json) task
Updated Bower main: pure.css

Running "compress:release" (compress) task
>> Compressed 43 files.

Done.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN purecss@1.0.1 license should be a valid SPDX license expression
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: iltorb@1.3.10 (node_modules/iltorb):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: iltorb@1.3.10 install: `detect-libc prebuild-install || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 757 packages from 408 contributors and audited 3280 packages in 36.137s
found 26 vulnerabilities (6 low, 6 moderate, 14 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by okuryu** [comment]
It seems to `iltorb` need to upgrade to the latest version. A patch for `grunt-contrib-compress` is open: https://github.com/gruntjs/grunt-contrib-compress/pull/216

A workaround for this issue is using Node.js v10.

**Comment by jamesbiv** [comment]
Hi Ryuichi

No worries, I just noticed that it seems to be an optional dependency anyway. I tried adding `"iltorb": ">=2.4.3"` to **package.json** but made little effect on the number of files produced. I'd just assume when the patch for grunt-contrib-compress is implemented the error will just go away.

If I run into further issues I'll raise a separate issue but for now I'll close this ticket as I see it more or less solved or a non-issue. 

Thanks for your help!

Regards JB

**Comment by jamesbiv** [comment]
Reopening with the following:

Changing **package.json** 
`"grunt-contrib-compress": "^1.4.3",` 
to 
` "grunt-contrib-compress": "1.3.0",` 

Solves the problem entirely.

**Comment by redonkulus** [comment]
@jamesbiv I would prefer to wait for the actual fix in grunt-contrib-compress, is there any progress on it? If not, we can downgrade.
